version: '{build}'

image:
  - macos
  - Ubuntu2004

configuration: Release

platform:
  - x64

for:
-
  matrix:
    only:
      - image: macos
  install:
    - curl -Ls https://micromamba.snakepit.net/api/micromamba/osx-64/latest | tar -xvj bin/micromamba
    - mv bin/micromamba ./micromamba
-
  matrix:
    only:
      - image: Ubuntu2004
  install:
    - wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba --strip-components=1

build_script:
  - ./micromamba shell init -s bash -p ~/micromamba
  - source ~/.bashrc
  - source ~/.bash_profile
  - hash -r
  - mkdir -p ~/micromamba/pkgs/
  - export MAMBA_ROOT_PREFIX=~/micromamba
  - export MAMBA_EXE=$(pwd)/micromamba
  - . $MAMBA_ROOT_PREFIX/etc/profile.d/mamba.sh

  # Install the packages required by xcube-cds (including xcube and its
  # dependencies), as well as the pytest package (needed for testing).
  - micromamba create --yes --file environment.yml
  - micromamba install --channel conda-forge pytest

  # Clone the xcube repository and install its dependencies using its conda
  # environment file
  - git clone https://github.com/dcs4cop/xcube $HOME/xcube
  - micromamba update --file $HOME/xcube/environment.yml

  # Remove the xcube conda package itself, because we want to install xcube
  # directly from its repository instead.
  - micromamba remove --prefix $HOME/mamba-env xcube

  # List the installed packages (useful for debugging).
  - micromamba list

  # Install xcube from its repository using setuptools.
  - cd $HOME/xcube
  - python setup.py install

  # Install xcube-cds from its repository using setuptools.
  - cd $APPVEYOR_BUILD_FOLDER
  - python setup.py install

  # Run the test suite.
  - pytest
