version: '{build}'

image:
  - macos
  - Ubuntu2004

configuration: Release

platform:
  - x64

for:
-
  matrix:
    only:
      - image: macos
  install:
    - curl -Ls https://micromamba.snakepit.net/api/micromamba/osx-64/latest | tar -xvj bin/micromamba
    - mv bin/micromamba ./micromamba
-
  matrix:
    only:
      - image: Ubuntu2004
  install:
    - wget -qO- https://micromamba.snakepit.net/api/micromamba/linux-64/latest | tar -xvj bin/micromamba --strip-components=1

build_script:
  - ./micromamba shell init -s bash -p ~/micromamba
  - source ~/.bashrc
  - source ~/.bash_profile
  - hash -r
  - mkdir -p ~/micromamba/pkgs/
  - export MAMBA_ROOT_PREFIX=~/micromamba
  - export MAMBA_EXE=$(pwd)/micromamba
  - . $MAMBA_ROOT_PREFIX/etc/profile.d/mamba.sh

  - git clone https://github.com/dcs4cop/xcube $HOME/xcube
  - micromamba create --name xc --file $HOME/xcube/environment.yml
  - micromamba activate xc
  - cd $HOME/xcube
  - python setup.py install

  - cd $APPVEYOR_BUILD_FOLDER
  - grep -v "^  - xcube" environment.yml > env_no_xcube.yml
  - micromamba update --yes --name xc --file env_no_xcube.yml
  - python setup.py install

  # Run the test suite.
  - micromamba activate xc
  - micromamba install --yes --name xc --channel conda-forge pytest attrs
  - python -c "import sys; print(sys.path)"
  - ls -1 $HOME/micromamba/envs/xc/lib/python3.9/site-packages/
  - python -m pytest
