name: xcube-cds
channels:
  - conda-forge
  - defaults
dependencies:
  # Required
  - xcube >= 0.5.0
  - cdsapi >= 0.2.7
  - python-dateutil >= 2.8.1
  - xarray >= 0.14.1
  - numpy >= 1.17
  - jsonschema >=3.2.0
