name: xcube-cds
channels:
  - conda-forge
  - defaults
dependencies:
  - cartopy >=0.17  # only required for demo notebooks
  - cdsapi >=0.2.7
  - jsonschema >=3.2.0
  - numpy >=1.17
  - python-dateutil >=2.8.1
  - xarray >=0.14.1
  - xcube >=0.5.2.dev1
